### ISSUE TITLE
Pool is destroyed error

### ISSUE THREAD

**Issue by iros** [bocoup/bots#102]
I seem to be getting this error on every message I sent my staging robocoup bot:

```
Error: Pool is destroyed
    at Pool.acquire (/Users/iros/dev/bocoup/bots/node_modules/pool2/lib/pool.js:163:12)
    at /Users/iros/dev/bocoup/bots/node_modules/knex/lib/client.js:204:19
    at tryCatcher (/Users/iros/dev/bocoup/bots/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/iros/dev/bocoup/bots/node_modules/knex/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/iros/dev/bocoup/bots/node_modules/knex/node_modules/bluebird/js/main/promise.js:70:37)
    at Client.acquireConnection (/Users/iros/dev/bocoup/bots/node_modules/knex/lib/client.js:200:12)
    at /Users/iros/dev/bocoup/bots/node_modules/knex/lib/runner.js:136:49
    at tryCatcher (/Users/iros/dev/bocoup/bots/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/Users/iros/dev/bocoup/bots/node_modules/knex/node_modules/bluebird/js/main/method.js:31:24)
    at Runner.ensureConnection (/Users/iros/dev/bocoup/bots/node_modules/knex/lib/runner.js:135:26)
    at Runner.run (/Users/iros/dev/bocoup/bots/node_modules/knex/lib/runner.js:30:31)
    at Raw.Target.then (/Users/iros/dev/bocoup/bots/node_modules/knex/lib/interface.js:27:43)
    at query (db.js:28:33)
    at handler (utilization.js:13:10)
    at index.js:106:12
    at conversation.js:13:68
    at tryCatcher (/Users/iros/dev/bocoup/bots/node_modules/bluebird/js/release/util.js:11:23)
    at Function.Promise.attempt.Promise.try (/Users/iros/dev/bocoup/bots/node_modules/bluebird/js/release/method.js:39:29)
    at Conversation.handleMessage (conversation.js:12:12)
    at Client.<anonymous> (index.js:96:28)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
```

I had run `npm run tunnel` and restarted my bot with `npm run start-dev`.
I still get the result I expect, so clearly it's accessing nest.

**Comment by tkellen** [comment]
closing in favor of #66
